spring:
  redis:
    host: localhost
    port: 6379

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${DATASOURCE_URL:jdbc:mariadb://localhost:3306/coupon?characterEncoding=UTF-8&serverTimezone=UTC}
    username: ${DATASOURCE_USERNAME:tester}
    password: ${DATASOURCE_PASSWORD:tester1234}
    hikari:
      max-lifetime: 600000
      maximum-pool-size: 40

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        show_sql: false
        format_sql: false

logging:
  level:
    root: INFO
    com.example.coupontest: INFO

